#ifndef _FRAM_LAYOUT_h
#define _FRAM_LAYOUT_h

#include "FRAM_Controller.h"

#define FRAM_SIZE 0x20000


#define FRAM_GENERIC_BASE 0
#define FRAM_GENERIC_SIZE 512

#define FRAM_CH0_LOW_LIMIT (FRAM_MEASUREMENT_INFO_BASE - 2) // 510 - 511
#define FRAM_CH0_HIGH_LIMIT (FRAM_CH0_LOW_LIMIT - 2) // 508 - 509
#define FRAM_CH1_LOW_LIMIT (FRAM_CH0_HIGH_LIMIT - 2) // 506 - 507
#define FRAM_CH1_HIGH_LIMIT (FRAM_CH1_LOW_LIMIT - 2) // 504 - 505
#define FRAM_CUTOFF_CH1     (FRAM_CH1_HIGH_LIMIT - 2)     // 502 - 503

// After generic region, FRAM is used for data storage
#define FRAM_MEASUREMENT_INFO_BASE (FRAM_GENERIC_BASE + FRAM_GENERIC_SIZE)
#define FRAM_MEASUREMENT_INFO_SIZE sizeof(measureInfo_t)

#define FRAM_DATA_BASE (FRAM_MEASUREMENT_INFO_BASE + FRAM_MEASUREMENT_INFO_SIZE)
#define FRAM_DATA_SIZE (FRAM_SIZE - FRAM_DATA_BASE)






#endif